# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://delta.rarus-crimea.ru/adding/noCardsOperations
Authorization: Basic 0JXQu9C40YHQtdC10LIg0JPQu9C10LEg0KHQtdGA0LPQtdC10LLQuNGHOjEzNzQ1NjM=
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="scopeOperation"

634.32
--WebAppBoundary--




###