# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://delta.rarus-crimea.ru/adding/operators
Authorization: Basic 0JHQvtGA0LjRgdC+0LIg0JTQsNC90LjRjdC70Ywg0JLQuNC60YLQvtGA0L7QstC40Yc6MzY4MDEwOA==
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nameOperators"

Кондратьев Захар Степанович
--WebAppBoundary--

--WebAppBoundary
Content-Disposition: form-data; name="accessLevel"

кассир
--WebAppBoundary--

###